### ISSUE TITLE
검색어 인덱싱 안됨

### ISSUE THREAD

**Issue by Pyohwan** [JakduK/jakduk-api#328]
```
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.jakduk.api.model.elasticsearch.EsSearchWord` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (byte[])"{"word":"검색","registerDate":"2018-09-10T23:31:41.752"}"; line: 1, column: 2]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67) ~[jackson-databind-2.9.6.jar!/:2.9.6]
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1451) ~[jackson-databind-2.9.6.jar!/:2.9.6]
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1027) ~[jackson-databind-2.9.6.jar!/:2.9.6]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1297) ~[jackson-databind-2.9.6.jar!/:2.9.6]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326) ~[jackson-databind-2.9.6.jar!/:2.9.6]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[jackson-databind-2.9.6.jar!/:2.9.6]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013) ~[jackson-databind-2.9.6.jar!/:2.9.6]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3091) ~[jackson-databind-2.9.6.jar!/:2.9.6]
	at com.jakduk.api.common.util.ObjectMapperUtils.readValue(ObjectMapperUtils.java:39) ~[classes!/:na]
	at com.jakduk.api.listener.ElasticsearchListener.receive(ElasticsearchListener.java:80) ~[classes!/:na]
	at sun.reflect.GeneratedMethodAccessor343.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]

```

**Comment by Pyohwan** [comment]
lombok 이슈. lombok 은 fadeout 하자.

**Comment by Pyohwan** [comment]
```
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.jakduk.api.model.embedded.ArticleItem` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (byte[])"{"id":"5b96a3a8df1b76449a4a0ef1","article":{"id":"5b7d61aadf1b761b0640751b","seq":995,"board":"FREE"},"content":"다시 두드려 보세여","galleries":[]}"; line: 1, column: 45] (through reference chain: com.jakduk.api.model.elasticsearch.EsComment["article"])
        at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67) ~[jackson-databind-2.9.6.jar!/:2.9.6]
        at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1451) ~[jackson-databind-2.9.6.jar!/:2.9.6]
        at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1027) ~[jackson-databind-2.9.6.jar!/:2.9.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1297) ~[jackson-databind-2.9.6.jar!/:2.9.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326) ~[jackson-databind-2.9.6.jar!/:2.9.6]
```
아직 남았음

**Comment by silverprize** [comment]
롬복 왜없앰?
@NoArgsConstructor 사용하셈

**Comment by Pyohwan** [comment]
https://oss.navercorp.com/mars/blitz/issues/123#issuecomment-2175413

* lombok 1.16.20에서 업그레이드 되면서 BREAKING CHANGE가 생겼다.
https://projectlombok.org/changelog
```
BREAKING CHANGE: lombok config key lombok.anyConstructor.suppressConstructorProperties is now deprecated and defaults to true, that is, by default lombok no longer automatically generates @ConstructorProperties annotations. New config key lombok.anyConstructor.addConstructorProperties now exists; set it to true if you want the old behavior. Oracle more or less broke this annotation with the release of JDK9, necessitating this breaking change.
```
* 스프링 부트 1.5.4
  * lombok 1.16.16
* 스프링 부트  1.5.10
  * lombok 1.16.20

### 원인 분석
* lombok 1.6.20 이전에는 생성자가 만들어질때 lombok이 기본적으로 `java.beans.@ConstructorProperties`를 사용했으나, lombok 1.6.20 에는 deprecated 되면서 더이상 `@ConstructorProperties` 를 붙혀주지 않는다.
* `@ConstructorProperties` 는 생성자의 파라미터 이름을 지정할때 사용.
* 나비효과
  * jackson 라이브러리로 deserialize 할 때 `@ConstructorProperties` 유무에 따라 동작 방식이 달라진다.
  * 생성자에 `@ConstructorProperties`가 달려있으면 인자를 받는 생성자를 사용해서 deserialize를 하고, 애노테이션이 없으면 기본생성자를 사용하게된다.

* 예제
```java
@Getter
@Builder
public class StorageCopyTask {
	@NotEmpty
	private String sourcePath;
	@NotEmpty
	private String destPath;
	private String callback;
	private Integer failoverCount;
}
```
  * 자바는 명시적으로 생성자를 생성 않는다면 기본 생성자를 사용한다.
  * @Builder 애너테이션은 내부적으로 파라미터가 있는 생성자를 생성하게 된다.
    * https://projectlombok.org/features/Builder 중간 즈음 참고
  * 이 경우 기본 생성자를 명시적으로 선언해주지 않으면 없는 셈이다.
* 결국 `@NoArgsConstructor` 를 붙히거나 혹은 직접 기본 생성자를 생성 해줘야 한다.

### 전역 설정 먹통
* lombok.config 파일을 프로젝트 루트 혹은 java 폴더에 넣어두면 된다고 lombok doc에 설명 되어 있으나, 동작하지 않았다.

### 해결책
1. lombok 버전을 1.6.18로 명시적으로 설정
1. lombok 버전을 따로 설정 하지 않고, 스프링 버전에 의존하도록 설정
  * 이럴 경우 `@Builder` 애너테이션이 있는 경우에는 `@NoArgsConstructor` 를 무조건 붙혀줘야 한다. 하는 김에 `@AllArgsConstructor` 도 해주자

### lombok을 계속 사용해야 할까?
* lombok이 jdk 버전 대응이 빠르지 않다.
  * jdk9 출시 2017.09. lombok의 jdk9 대응 2018.01
  * jdk10 출시 2018.03. lombok의 jdk9 대응 현재 못함
  * LTS 버전인 jdk11 은 조속히 대응가능할까?
* lombok changelog 지켜볼 필요
  * 또 언제 BREAKING CHANGE가 업데이트 될지도 모르니
* fade-out 할 경우 대응책 필요
  * `@Builder`, `@Slf4j` 등 유용하게 쓰는 기능들을 대체할만한 것이 필요.

* 참고
  * http://multifrontgarden.tistory.com/222

**Comment by silverprize** [comment]
탈 자바하고 스칼라로 갑시다.

**Comment by Pyohwan** [comment]
스칼라로 스프링 되나요? 스칼라 라이브러리로 얼마 없을것 같은데
