### ISSUE TITLE
이클립스에서 .ymi 화일 개발환경 설정 문의드립니다.

### ISSUE THREAD

**Issue by isolet169** [JakduK/jakduk-api#362]
안녕하세요. 스프링 웹 오픈소스를 찾다가 오늘의유머에서  http://www.todayhumor.co.kr/board/view.php?table=programmer&no=7453
글을 보고 이 소스를 찾아오게된 학생입니다.
실무에서 개발자분들이 소스를 어떻게짜는지 궁금해서 소스를 제컴퓨터에서 실행해보고싶은데요,
위키 참조해서, 이클립스에서 깃클론 하고, 몽고DB와 rabbitmq, elasticsearch 등등 설치한후 이클립스 그래들에서 bootrun task로 실행하였는데, "노드를 찾을수없다. 큐를 찾을수없다" 이런 에러가 나오더군요. 제가 자바와 스프링만 공부해보고 네트워크쪽은 문외한이라 20시간넘게 구글검색으로 에러를 찾아서 고쳐보아도 계속 에러만 납니다. 제 생각으로는  application-default.ymi, application-dev.ymi, application-prod.ymi, application.ymi 이걸 고치고 rabbitmq와 mongodb와 elasticsearch에 어떻게 설정을 해줘야 제대로 실행될것 같은데요,
어떻게 설정해야 할지 조언해주신다면 정말 감사하겠습니다.

OS는 윈도우10, 개발툴은 이클립스이고요, 
pplication.ymi의 mail의 username password에는 제 구글계정과 비번을 넣었고요, 
 application-default.ymi, application-dev.ymi, application-prod.ymi 의
spring-data-elasticsearch 의 cluseter-name은 jakduk-elasticsearch로 하고, cluster-nodes: 211.183.7.116:9300 로 한후, 
C:\elasticsearch-2.4.0\config\elasticsearch.ymi의 cluster.name: jakduk-elasticsearch 로 설정하고,
network.host: 0.0.0.0 로 설정하였습니다.
 
application-default.ymi, application-dev.ymi, application-prod.ymi 의 rabbitmq의 address에는 0.0.0.0을 넣었고요, username에 testuser을 넣고, password에 testuser을 넣었습니다.
제컴퓨터의 rabbmitmq에서 administartor권한으로 아이디 testuser password testuser로 계정을 만들어 두었고요, 127,0.0.1/15672에서 testuser/testuser로 로그인하면 잘 됩니다.

application-default.ymi, application-dev.ymi, application-prod.ymi 의 mongodb의 database를 jakduk_test로 설정해 놓았고요, host: http://127.0.0.1:27017로 설정해 놓았습니다. 제 컴퓨터의 명령프롬프트에서 mongod 치면 제대로 mongodb에 접속 됩니다.

이렇게 해보았느데 잘 안되서요, 여기서 어떻게 뭘 변경하고, 제컴퓨터의 프로그램을 어떻게 제대로 설정해야 작두왕으로 접속이 가능한지 조언 부탁드립니다. 좋은하루되세요.

**Comment by Pyohwan** [comment]
@isolet169 
안녕하세요. 반갑습니다.
20시간이나 고민하셨다니 많이 고생하셨네요.

몇년전에 로컬에서 띄워볼수 있도록 위키를 만든적이 있는데요.
https://github.com/JakduK/jakduk-api/wiki

근데, 지금과 저 위키를 작성할 시점과 변화된 점이 많습니다.

일단 jakduk-api 와 jakduk-web 이 분리되었고, RabbitMQ도 추가가 됐죠. 적어주신 메시지를 토대로 볼때에는 RabbitMQ 쪽에서 문제가 생긴것 같네요.
일단 `application-default.yml` 에 있는 rabbitbq.queues 하위에 있는 `[queue].enabled` 를 false 로 해서 되는지 봐주세요.

그리고 향후 시간날때 위키도 갱신해 두겠습니다.
즐거운 github 되세요.

**Comment by isolet169** [comment]
@Pyohwan 
안녕하세요. 바쁘신 와중에 답변 감사합니다.
말씀해 주신대로 false로 설정 했습니다만,

2019-10-25 10:59:14,650 [http-nio-8080-exec-3] [DEBUG] [NioEndpoint.log:173] - Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@a0953a5:org.apache.tomcat.util.net.NioChannel@236feb77:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:8080 remote=/0:0:0:0:0:0:0:1:56458]], Read direct from socket: [0]
2019-10-25 10:59:14,650 [http-nio-8080-exec-3] [DEBUG] [Http11Processor.log:173] - Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@a0953a5:org.apache.tomcat.util.net.NioChannel@236feb77:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:8080 remote=/0:0:0:0:0:0:0:1:56458]], Status in: [OPEN_READ], State out: [OPEN]
2019-10-25 10:59:25,437 [http-nio-8080-exec-4] [DEBUG] [SocketWrapperBase.log:173] - Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@666dd1e7:org.apache.tomcat.util.net.NioChannel@68aa3282:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:8080 remote=/0:0:0:0:0:0:0:1:56457]], Read from buffer: [0]
2019-10-25 10:59:25,438 [http-nio-8080-exec-4] [DEBUG] [Http11Processor.log:175] - Error parsing HTTP request header
java.io.EOFException: null
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer(NioEndpoint.java:1239) ~[tomcat-embed-core-9.0.26.jar:9.0.26]
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.read(NioEndpoint.java:1139) ~[tomcat-embed-core-9.0.26.jar:9.0.26]
	at org.apache.coyote.http11.Http11InputBuffer.fill(Http11InputBuffer.java:735) ~[tomcat-embed-core-9.0.26.jar:9.0.26]
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:353) ~[tomcat-embed-core-9.0.26.jar:9.0.26]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:292) ~[tomcat-embed-core-9.0.26.jar:9.0.26]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-9.0.26.jar:9.0.26]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860) [tomcat-embed-core-9.0.26.jar:9.0.26]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589) [tomcat-embed-core-9.0.26.jar:9.0.26]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.26.jar:9.0.26]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_211]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.26.jar:9.0.26]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_211]
2019-10-25 10:59:25,439 [http-nio-8080-exec-4] [DEBUG] [Http11Processor.log:173] - Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@666dd1e7:org.apache.tomcat.util.net.NioChannel@68aa3282:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:8080 remote=/0:0:0:0:0:0:0:1:56457]], Status in: [OPEN_READ], State out: [CLOSED]
2019-10-25 10:59:25,439 [http-nio-8080-exec-4] [DEBUG] [NioEndpoint.log:175] - Calling [org.apache.tomcat.util.net.NioEndpoint@41fed14f].closeSocket([org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@666dd1e7:org.apache.tomcat.util.net.NioChannel@68aa3282:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:8080 remote=/0:0:0:0:0:0:0:1:56457]])
java.lang.Exception: null
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doClose(NioEndpoint.java:1165) [tomcat-embed-core-9.0.26.jar:9.0.26]
	at org.apache.tomcat.util.net.SocketWrapperBase.close(SocketWrapperBase.java:394) [tomcat-embed-core-9.0.26.jar:9.0.26]
	at org.apache.tomcat.util.net.NioEndpoint$Poller.cancelledKey(NioEndpoint.java:667) [tomcat-embed-core-9.0.26.jar:9.0.26]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1592) [tomcat-embed-core-9.0.26.jar:9.0.26]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.26.jar:9.0.26]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_211]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.26.jar:9.0.26]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_211]
2019-10-25 10:59:25,439 [http-nio-8080-exec-4] [DEBUG] [LimitLatch.log:173] - Counting down[http-nio-8080-exec-4] latch=2
2019-10-25 10:59:40,113 [Catalina-utility-1] [DEBUG] [ManagerBase.log:173] - Start expire sessions StandardManager at 1571968780113 sessioncount 0
2019-10-25 10:59:40,114 [Catalina-utility-1] [DEBUG] [ManagerBase.log:173] - End expire sessions StandardManager processingTime 1 expired sessions: 0
2019-10-25 11:00:15,460 [http-nio-8080-exec-5] [DEBUG] [NioEndpoint.log:175] - Calling [org.apache.tomcat.util.net.NioEndpoint@41fed14f].closeSocket([org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@a0953a5:org.apache.tomcat.util.net.NioChannel@236feb77:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:8080 remote=/0:0:0:0:0:0:0:1:56458]])
java.lang.Exception: null
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doClose(NioEndpoint.java:1165) [tomcat-embed-core-9.0.26.jar:9.0.26]
	at org.apache.tomcat.util.net.SocketWrapperBase.close(SocketWrapperBase.java:394) [tomcat-embed-core-9.0.26.jar:9.0.26]
	at org.apache.tomcat.util.net.NioEndpoint$Poller.cancelledKey(NioEndpoint.java:667) [tomcat-embed-core-9.0.26.jar:9.0.26]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1592) [tomcat-embed-core-9.0.26.jar:9.0.26]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.26.jar:9.0.26]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_211]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.26.jar:9.0.26]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_211]
2019-10-25 11:00:15,460 [http-nio-8080-exec-5] [DEBUG] [LimitLatch.log:173] - Counting down[http-nio-8080-exec-5] latch=1

이렇게 에러가 뜨네요. api와 web을 분리하셨다고 하셨는데요, 혹시 이클립스에서 실행할떄 프로젝트 두개를 한꺼번에 실행해야 되는것인가요?

**Comment by Pyohwan** [comment]
@isolet169 
네 jakduk-api 는 말그대로 API 요청, 응답이 가능하고, jakduk-web 은 vuejs 기반의 html 를 만들어서 브라우저에서 보여줍니다.
